---
output:
  pdf_document:
    latex_engine: lualatex
header-includes:
  - \usepackage[default,oldstyle,scale=0.95]{opensans}
  - \usepackage[T1]{fontenc}

params: 
  x: WAVE0
  data: data.frame()
  focal.predictor0: ""
  wgt: WGT0
  psu: PSU
  strata: STRATA
  tb.num: 1
  tb.cap: "Sample summary."
  fn.txt: ""
---

\pagestyle{empty}
\setmainfont{opensans}

```{r}
#| label: setup
#| include: FALSE

set_flextable_defaults(font.family = "Open Sans",font.size = 10)

knitr::opts_chunk$set(
  echo = FALSE,
  ft.tabcolsep=0, ft.latex.float = "none", ft.arraystretch=1,
  tab.cap.pre = "", tab.cap.sep = "",
  warning = FALSE, message = FALSE,
  cache = TRUE,
  cache.extra = list(
    R.version, sessionInfo(), format(Sys.Date(), '%Y-%m')
  )
)
## extract parameters
x = params$x
data = params$data
focal.predictor0 = params$focal.predictor0
wgt = params$wgt
psu = params$psu
strata = params$strata
tb.num = params$tb.num
tb.cap = params$tb.cap
fn.txt = params$fn.txt

```


```{r}
#| label: build-table

## create table
  suppressWarnings({
    sumtab <-  data %>%
            as_survey_design(
              #ids = {{psu}},
              strata = {{strata}},
              weights = {{wgt}}
            ) %>%
            tbl_svysummary(
              by = {{x}},
              include = c(
                any_of(focal.predictor0),
                AGE_GRP,
                AGE,
                GENDER,
                MARITAL_STATUS,
                EDUCATION_3, EMPLOYMENT,
                ATTEND_SVCS,
                BORN_COUNTRY,
                PARENTS_12YRS, SVCS_12YRS, MOTHER_RELATN, FATHER_RELATN,
                OUTSIDER, ABUSED, HEALTH_GROWUP, INCOME_12YRS, REL1
              ),
              label = list(
                AGE_GRP ~ "Year of birth",
                AGE ~ "Age of participant",
                GENDER ~ "Gender",
                #RACE1 ~ "Race/ethnicity",
                MARITAL_STATUS ~ "Respondent marital status",
                EMPLOYMENT ~ "Employment status",
                #INCOME ~ "Self-reported income",
                ATTEND_SVCS ~ "Current religious service attendance",
                EDUCATION_3 ~ "Education (years)",
                BORN_COUNTRY ~ "Immigration status",
                PARENTS_12YRS ~ "Parental marital status around age 12",
                MOTHER_RELATN ~ "Relationship with mother when growing up",
                FATHER_RELATN ~ "Relationship with father when growing up",
                OUTSIDER ~ "Felt like an outsider in family when growing up",
                ABUSED ~ "Experienced abuse when growing up",
                HEALTH_GROWUP ~ "Self-rated health when growing up",
                INCOME_12YRS ~ "Subjective financial status of family growing up",
                SVCS_12YRS ~ "Religious service attendance around age 12",
                REL1 ~ "Religious affiliation growing up"
              ),
              type = list(
                AGE ~ "continuous2",
                all_continuous() ~ "continuous2"
              ),
              statistic = list(
                all_continuous() ~ c("    {mean}", "    {sd}", "    {min}, {max}"),
                all_categorical() ~ "{n} ({p}%)"
              ),
              digits = list(
                all_continuous() ~ c(1,1,1,1),
                all_categorical() ~ list(label_style_number(digits=0), label_style_percent0(digits = 1))
              ),
              missing_text = "    (Missing)",
              missing_stat = "{N_miss} ({p_miss}%)"
            ) %>%
            add_stat_label(
              label = all_continuous() ~ c("    Mean", "    Standard Deviation", "    Min, Max")
            ) %>%
            modify_header(label ~ "**Characteristic**") %>%
            italicize_labels()
  })
  

footnote.text <- "Note. N (%); this table is based on non-imputed data. Cumulative percentages for variables may not add up to 100% due to rounding."
footnote.text <- paste(footnote.text, fn.txt)

tb.note.summarytab <- as_paragraph(as_chunk(footnote.text, props = fp_text_default(font.family = "Open Sans", font.size = 9)))
  
```


 
```{r}
#| label: print-table

knitr::opts_chunk$set(
  echo = FALSE,
  ft.tabcolsep=0, ft.latex.float = "none", ft.arraystretch=1,
  tab.cap.pre = "", tab.cap.sep = ""
)

  sumtab %>%
    as_flex_table() %>%
    autofit() %>%
    format_flex_table(pg.width = 21 / 2.54 - 2)  %>%
    add_footer_row(
      values = tb.note.summarytab, top = FALSE, colwidths=3
    ) %>%
    add_header_lines(
      as_paragraph(
        as_chunk(tb.cap, props = fp_text_default(font.family = "Open Sans", font.size = 11))
      )
    )


```
