---
output:
  pdf_document:
    latex_engine: lualatex
header-includes:
  - \usepackage[default,oldstyle,scale=0.95]{opensans}
  - \usepackage[T1]{fontenc}

params: 
  x: WAVE0
  data: data.frame()
  OUTCOME.VEC0: ""
  OUTCOME.VEC.LABELS: ""
  wgt: WGT0
  psu: PSU
  strata: STRATA
  tb.num: 2
  tb.cap: "Sample summary."
  fn.txt: ""
  cache.file: ""
  start.time: ""
  ignore.cache: TRUE
---

\pagestyle{empty}
\setmainfont{opensans}

```{r}
#| label: setup
#| include: FALSE

set_flextable_defaults(font.family = "Open Sans",font.size = 10)

knitr::opts_chunk$set(
  echo = FALSE,
  ft.tabcolsep=0, ft.latex.float = "none", ft.arraystretch=1,
  tab.cap.pre = "", tab.cap.sep = "",
  warning = FALSE, message = FALSE
)
## extract parameters
data = params$data
OUTCOME.VEC0 = params$OUTCOME.VEC0
OUTCOME.VEC.LABELS = params$OUTCOME.VEC.LABELS
wgt = params$wgt
psu = params$psu
strata = params$strata
tb.num = params$tb.num
tb.cap = params$tb.cap
fn.txt = params$fn.txt
cache.file = params$cache.file
start.time = params$start.time
ignore.cache = params$ignore.cache


```


```{r}
#| label: build-table


if(ignore.cache | !(file.exists(cache.file)) | (file.info(cache.file)$ctime < start.time) ){
  ## create table
  sumtab <-  data %>%
    as_survey_design(
      #ids = {{psu}},
      strata = {{strata}},
      weights = {{wgt}}
    ) %>%
    tbl_svysummary(
      by = WAVE0,
      include = c(
        any_of(OUTCOME.VEC0[str_detect(OUTCOME.VEC0, "INCOME_QUINTILE", negate=TRUE)])
      ),
      label = OUTCOME.VEC.LABELS,
      type = list(
        all_continuous() ~ "continuous2",
        contains("NUM_CHILDREN") ~ "continuous2",
        contains("CIGARETTES") ~ "continuous2",
        contains("DAYS_EXERCISE") ~ "continuous2",
        contains("DRINKS") ~ "continuous2"
      ),
      statistic = list(
        all_continuous() ~ c("    {mean}", "    {sd}", "    {min}, {max}"),
        all_categorical() ~ "{n} ({p}%)"
      ),
      digits = list(
        all_continuous() ~ c(1,1,1,1),
        all_categorical() ~ list(label_style_number(digits=0), label_style_percent0(digits = 1))
      ),
      missing_text = "    (Missing)",
      missing_stat = "{N_miss} ({p_miss}%)"
    ) %>%
    add_stat_label(
      label = all_continuous() ~ c("    Mean", "    Standard Deviation", "    Min, Max")
    ) %>%
    modify_header(label ~ "**Outcome**") %>%
    italicize_labels()
  
  save(sumtab, file=cache.file)
} else {
  load(cache.file)
}

footnote.text <- "*Note*. N (%); this table is based on non-imputed data. Cumulative percentages for variables may not add up to 100% due to rounding."
footnote.text <- paste(footnote.text, fn.txt)

tb.note.summarytab <- as_paragraph(as_chunk(footnote.text, props = fp_text_default(font.family = "Open Sans", font.size = 9)))

```



```{r}
#| label: print-table

knitr::opts_chunk$set(
  echo = FALSE,
  ft.tabcolsep=0, ft.latex.float = "none", ft.arraystretch=1,
  tab.cap.pre = "", tab.cap.sep = ""
)

sumtab %>%
  as_flex_table() %>%
  autofit() %>%
  width(j=2,width=1.5)%>%
  width(j=3,width=1.5)%>%
  format_flex_table(pg.width = 21 / 2.54 - 2)  %>%
  add_footer_row(
    values = tb.note.summarytab, top = FALSE, colwidths=3
  ) %>%
  add_header_lines(
    as_paragraph(
      as_chunk(tb.cap, props = fp_text_default(font.family = "Open Sans", font.size = 11))
    )
  )


```
