---
output:
  pdf_document:
    latex_engine: lualatex
  word_document:
    reference_docx: "template_landscape_wide1.docx"
header-includes:
  - \usepackage[default,oldstyle,scale=0.95]{opensans}
  - \usepackage[T1]{fontenc}
geometry: "paperheight=25in,paperwidth=42in,margin=1in"
params: 
  x: WAVE0
  y: COUNTRY
  data: data.frame()
  focal.predictor0: ""
  baseline.pred0: ""
  wgt: WGT0
  psu: PSU
  strata: STRATA
  tb.cap: "Sample summary."
  fn.txt: ""
  countries.included: ""
  cache.file: ""
  start.time: ""
  ignore.cache: TRUE
  file.xlsx: ""
---

\pagestyle{empty}
\setmainfont{opensans}

```{r}
#| label: setup
#| include: FALSE

set_flextable_defaults(font.family = "Open Sans",font.size = 9)

knitr::opts_chunk$set(
  echo = FALSE,
  ft.tabcolsep=0, ft.latex.float = "none", ft.arraystretch=1,
  tab.cap.pre = "", tab.cap.sep = "",
  warning = FALSE, message = FALSE
)
## extract parameters
x = params$x
y = params$y
data = params$data
focal.predictor0 = params$focal.predictor0
baseline.pred0 = params$baseline.pred0
wgt = params$wgt
psu = params$psu
strata = params$strata
tb.cap = params$tb.cap
fn.txt = params$fn.txt
countries.included = params$countries.included
cache.file = params$cache.file
start.time = params$start.time
ignore.cache = params$ignore.cache
file.xlsx = params$file.xlsx


```


```{r}
#| label: build-table

nC <- 1 + 2*length(countries.included)

if(ignore.cache | !(file.exists(cache.file)) | (file.info(cache.file)$ctime < start.time) ){
## create table
  sumtab <- NULL
  sum.error <- "none"
  try({
  sumtab <- data %>%
    #filter(COUNTRY %in% countries.included) %>%
    # as_survey_design(
    #   #strata = {{strata}},
    #   weights = {{wgt}}
    # ) %>%
    tbl_strata(
      strata = {{y}},
      .tbl_fun = \(xdat){
        xdat |>
        tbl_summary(
          by = {{x}},
          include = c(
            any_of(focal.predictor0),
            any_of(baseline.pred0)
          ),
          type = list(
            all_continuous() ~ "continuous2"
          ),
          statistic = list(
            all_continuous() ~ c("    {mean}", "    {sd}"),
            all_categorical() ~ "{p}%"
          ),
          label = list(
            AGE_GRP ~ "Year of birth",
            GENDER ~ "Gender",
            MARITAL_STATUS ~ "Respondent marital status",
            EMPLOYMENT ~ "Employment status",
            ATTEND_SVCS ~ "Current religious service attendance",
            EDUCATION_3 ~ "Education (years)",
            BORN_COUNTRY ~ "Immigration status",
            PARENTS_12YRS ~ "Parental marital status around age 12",
            MOTHER_RELATN ~ "Relationship with mother when growing up",
            FATHER_RELATN ~ "Relationship with father when growing up",
            OUTSIDER ~ "Felt like an outsider in family when growing up",
            ABUSED ~ "Experienced abuse when growing up",
            HEALTH_GROWUP ~ "Self-rated health when growing up",
            INCOME_12YRS ~ "Subjective financial status of family growing up",
            SVCS_12YRS ~ "Religious service attendance around age 12",
            REL1 ~ "Religious affiliation growing up"
          ),
          digits = list(
            all_continuous() ~ c(1,1),
            all_categorical() ~ list(label_style_percent0(digits = 1))
          ),
          missing_text = "    (Missing)",
          missing_stat = "{N_miss}"
        ) %>%
        #modify_header(all_stat_cols() ~ "**{level}**") %>%
        modify_header(label ~ "**Characteristic**") %>%
        add_stat_label(
          label = all_continuous() ~ c("    Mean", "    Standard Deviation")
        )
      },
      .header = "**{strata}**"
    ) %>%
    italicize_labels()
  })

} else {
  load(cache.file)
}

footnote.text <- "Note. N (%); this table is based on non-imputed data. Cumulative percentages for variables may not add up to 100% due to rounding."
footnote.text <- paste(footnote.text, fn.txt)

tb.note <- as_paragraph(as_chunk(footnote.text, props = fp_text_default(font.family = "Open Sans", font.size = 9)))

```



```{r}
#| label: print-table

knitr::opts_chunk$set(
  echo = FALSE,
  ft.tabcolsep=0, ft.latex.float = "none", ft.arraystretch=1,
  tab.cap.pre = "", tab.cap.sep = ""
)


if(sum.error == "none"){
  
  try({
ft <- sumtab %>%
  as_flex_table() %>%
  autofit() %>%
  format_flex_table(pg.width = 40) %>%
  bg(
    j = c(2 + seq(0,nC,4), 3 + seq(0,nC,4)), bg="grey90",part = "all"
  ) %>%
  add_footer_lines(
    values = tb.note, top = FALSE
  ) %>%
  add_header_lines(
    as_paragraph(
      as_chunk(tb.cap, props = fp_text_default(font.family = "Open Sans", font.size = 11))
    )
  ) %>%
  hline(i=1, part = "header") %>%
  align(i=2, align = "center", part = "header")

ft

})
} else {
  print("Could not construct summary table.")
}

## only needs to be ran once
if(ignore.cache | !(file.exists(cache.file)) | (file.info(cache.file)$ctime < start.time) ){
  gfs_append_to_xlsx(file.xlsx, ft, tb.cap)
  save(sumtab, sum.error, file=cache.file)
}
```
